theme: jekyll-theme-cayman

# Setup
title:        Lyzh 的桌游小屋
tagline:      包含一些原创的模组资源
baseurl:      https://zhihang-sboardhouse.github.io
paginate:     1
locale:       "zh-cn"

# About/contact
author:
  name:       Zhihang-Liu (Lyzh)
  url:        https://github.com/Zhihang-Liu

permalink: /:title

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
